### ISSUE TITLE
Add shallow routing to modals

### ISSUE THREAD

**Issue by LeoDog896** [CoasterFan5/Clubsaurus#18]

**Comment by CoasterFan5** [comment]
@LeoDog896 can you elaborate on this?

**Comment by LeoDog896** [comment]
https://kit.svelte.dev/docs/shallow-routing

**Comment by LeoDog896** [comment]
Framework setup with https://github.com/CoasterFan5/Clubsaurus/commit/0ec47aabf0bd8a18a52efbf434570cfba6b07840

**Comment by LeoDog896** [comment]
https://github.com/CoasterFan5/Clubsaurus/commit/ce7cb480ecad8810416351f64806560a44945b24
