### ISSUE TITLE
Make tiptap editor look good

### ISSUE THREAD

**Issue by LeoDog896** [CoasterFan5/Clubsaurus#19]

**Comment by CoasterFan5** [comment]
Improvements made in 6aa400cc9378ce0b4120f074acc21de025f20675

**Comment by CoasterFan5** [comment]
Closing. Not a priority at this moment, may investigate later

**Comment by CoasterFan5** [comment]
what do you even mean by this

**Comment by LeoDog896** [comment]
> what do you even mean by this

it looks bad
