### ISSUE TITLE
Allow private / public orgs

### ISSUE THREAD

**Issue by CoasterFan5** [CoasterFan5/Clubsaurus#20]
Ability to create public organizations where clubs can be viewed publicly and maybe a global calendar too.

**Comment by LeoDog896** [comment]
https://github.com/CoasterFan5/Clubsaurus/commit/575bee4233b0679d99e391504ed58e4d0040842e

**Comment by LeoDog896** [comment]
and https://github.com/CoasterFan5/Clubsaurus/commit/053c0706a638e97b37b700a413926f128aadbeeb
